### ISSUE TITLE
Build fails when there has never been a release.

### ISSUE THREAD

**Issue by ecassady** [scalawag/sbt-gitflow#3]
If you try to build a project that has never been released, you get the following Exception:

java.lang.ExceptionInInitializerError
    at UtilsBuild$$anonfun$22.apply(UtilsBuild.scala:56)
    at UtilsBuild$$anonfun$22.apply(UtilsBuild.scala:56)
    at sbt.Project$ProjectDef.settings$lzycompute(Project.scala:225)
    at sbt.Project$ProjectDef.settings(Project.scala:225)
    at sbt.Project$class.copy$default$6(Project.scala:88)
    at sbt.Project$$anon$2.copy$default$6(Project.scala:274)
    at sbt.Project$$anonfun$dependsOn$4.apply(Project.scala:132)
    at sbt.Project$$anonfun$dependsOn$4.apply(Project.scala:132)
    at sbt.Project$ProjectDef.settings$lzycompute(Project.scala:225)
    at sbt.Project$ProjectDef.settings(Project.scala:225)
    at sbt.Project$class.copy$default$6(Project.scala:88)
    at sbt.Project$$anon$2.copy$default$6(Project.scala:274)
    at sbt.Project$$anonfun$configs$4.apply(Project.scala:129)
    at sbt.Project$$anonfun$configs$4.apply(Project.scala:129)
    at sbt.Project$ProjectDef.settings$lzycompute(Project.scala:225)
    at sbt.Project$ProjectDef.settings(Project.scala:225)
    at sbt.Project$class.copy$default$6(Project.scala:88)
    at sbt.Project$$anon$2.copy$default$6(Project.scala:274)
    at sbt.Load$$anonfun$resolveBase$1$$anonfun$apply$17.apply(Load.scala:383)
    at sbt.Load$$anonfun$resolveBase$1$$anonfun$apply$17.apply(Load.scala:383)
    at sbt.Project$ProjectDef.settings$lzycompute(Project.scala:225)
    at sbt.Project$ProjectDef.settings(Project.scala:225)
    at sbt.Load$.sbt$Load$$expandSettings$1(Load.scala:674)
    at sbt.Load$$anonfun$sbt$Load$$expandSettings$1$2.apply(Load.scala:680)
    at sbt.Load$$anonfun$sbt$Load$$expandSettings$1$2.apply(Load.scala:680)
    at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
    at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
    at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
    at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
    at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
    at sbt.Load$.sbt$Load$$expandSettings$1(Load.scala:680)
    at sbt.Load$.resolveProject(Load.scala:682)
    at sbt.Load$.finalizeProject$1(Load.scala:549)
    at sbt.Load$.discoverAndLoad$1(Load.scala:562)
    at sbt.Load$.loadTransitive(Load.scala:570)
    at sbt.Load$.loadProjects$1(Load.scala:442)
    at sbt.Load$.loadUnit(Load.scala:446)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
    at sbt.BuildLoader.apply(BuildLoader.scala:140)
    at sbt.Load$.loadAll(Load.scala:334)
    at sbt.Load$.loadURI(Load.scala:289)
    at sbt.Load$.load(Load.scala:285)
    at sbt.Load$.load(Load.scala:276)
    at sbt.Load$.apply(Load.scala:130)
    at sbt.Load$.defaultLoad(Load.scala:36)
    at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$.process(Command.scala:92)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.State$$anon$1.process(State.scala:184)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.MainLoop$.next(MainLoop.scala:98)
    at sbt.MainLoop$.run(MainLoop.scala:91)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
    at sbt.Using.apply(Using.scala:24)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
    at sbt.MainLoop$.runLogged(MainLoop.scala:24)
    at sbt.StandardMain$.runManaged(Main.scala:53)
    at sbt.xMain.run(Main.scala:28)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.util.NoSuchElementException: next on empty iterator
    at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
    at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
    at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:64)
    at scala.collection.IterableLike$class.head(IterableLike.scala:91)
    at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$head(ArrayBuffer.scala:47)
    at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:120)
    at scala.collection.mutable.ArrayBuffer.head(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.last(TraversableLike.scala:455)
    at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$last(ArrayBuffer.scala:47)
    at scala.collection.IndexedSeqOptimized$class.last(IndexedSeqOptimized.scala:126)
    at scala.collection.mutable.ArrayBuffer.last(ArrayBuffer.scala:47)
    at org.scalawag.sbt.gitflow.GitFlow.mostRecentReleaseVersion(GitFlow.scala:92)
    at org.scalawag.sbt.gitflow.GitFlow.nextReleaseVersion(GitFlow.scala:95)
    at org.scalawag.sbt.gitflow.GitFlow.org$scalawag$sbt$gitflow$GitFlow$$developArtifactVersion(GitFlow.scala:98)
    at org.scalawag.sbt.gitflow.GitFlow.currentBranchArtifactVersion(GitFlow.scala:158)
    at org.scalawag.sbt.gitflow.GitFlow.identifiedVersion(GitFlow.scala:193)
    at org.scalawag.sbt.gitflow.GitFlow.versionOrZero(GitFlow.scala:205)
    at BuildSettings$.<init>(UtilsBuild.scala:12)
    at BuildSettings$.<clinit>(UtilsBuild.scala)
    at UtilsBuild$$anonfun$22.apply(UtilsBuild.scala:56)
    at UtilsBuild$$anonfun$22.apply(UtilsBuild.scala:56)
    at sbt.Project$ProjectDef.settings$lzycompute(Project.scala:225)
    at sbt.Project$ProjectDef.settings(Project.scala:225)
    at sbt.Project$class.copy$default$6(Project.scala:88)
    at sbt.Project$$anon$2.copy$default$6(Project.scala:274)
    at sbt.Project$$anonfun$dependsOn$4.apply(Project.scala:132)
    at sbt.Project$$anonfun$dependsOn$4.apply(Project.scala:132)
    at sbt.Project$ProjectDef.settings$lzycompute(Project.scala:225)
    at sbt.Project$ProjectDef.settings(Project.scala:225)
    at sbt.Project$class.copy$default$6(Project.scala:88)
    at sbt.Project$$anon$2.copy$default$6(Project.scala:274)
    at sbt.Project$$anonfun$configs$4.apply(Project.scala:129)
    at sbt.Project$$anonfun$configs$4.apply(Project.scala:129)
    at sbt.Project$ProjectDef.settings$lzycompute(Project.scala:225)
    at sbt.Project$ProjectDef.settings(Project.scala:225)
    at sbt.Project$class.copy$default$6(Project.scala:88)
    at sbt.Project$$anon$2.copy$default$6(Project.scala:274)
    at sbt.Load$$anonfun$resolveBase$1$$anonfun$apply$17.apply(Load.scala:383)
    at sbt.Load$$anonfun$resolveBase$1$$anonfun$apply$17.apply(Load.scala:383)
    at sbt.Project$ProjectDef.settings$lzycompute(Project.scala:225)
    at sbt.Project$ProjectDef.settings(Project.scala:225)
    at sbt.Load$.sbt$Load$$expandSettings$1(Load.scala:674)
    at sbt.Load$$anonfun$sbt$Load$$expandSettings$1$2.apply(Load.scala:680)
    at sbt.Load$$anonfun$sbt$Load$$expandSettings$1$2.apply(Load.scala:680)
    at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
    at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
    at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
    at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
    at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
    at sbt.Load$.sbt$Load$$expandSettings$1(Load.scala:680)
    at sbt.Load$.resolveProject(Load.scala:682)
    at sbt.Load$.finalizeProject$1(Load.scala:549)
    at sbt.Load$.discoverAndLoad$1(Load.scala:562)
    at sbt.Load$.loadTransitive(Load.scala:570)
    at sbt.Load$.loadProjects$1(Load.scala:442)
    at sbt.Load$.loadUnit(Load.scala:446)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
    at sbt.BuildLoader.apply(BuildLoader.scala:140)
    at sbt.Load$.loadAll(Load.scala:334)
    at sbt.Load$.loadURI(Load.scala:289)
    at sbt.Load$.load(Load.scala:285)
    at sbt.Load$.load(Load.scala:276)
    at sbt.Load$.apply(Load.scala:130)
    at sbt.Load$.defaultLoad(Load.scala:36)
    at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$.process(Command.scala:92)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.State$$anon$1.process(State.scala:184)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.MainLoop$.next(MainLoop.scala:98)
    at sbt.MainLoop$.run(MainLoop.scala:91)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
    at sbt.Using.apply(Using.scala:24)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
    at sbt.MainLoop$.runLogged(MainLoop.scala:24)
    at sbt.StandardMain$.runManaged(Main.scala:53)
    at sbt.xMain.run(Main.scala:28)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ExceptionInInitializerError
[error] Use 'last' for the full log.

**Comment by ecassady** [comment]
If you have an open release branch (i.e. release/0.1.0), then you can enable sbt-gitflow on develop and successfully build 0.2-SNAPSHOT

**Comment by justinp** [comment]
I made it so that it defaults to 0.0-SNAPSHOT if there is no prior release.  I don't know if that makes sense.

This is in 1.2.1.
